version: '3.8'

services:
  # Redis - State store and Pub/Sub
  redis:
    image: redis:7-alpine
    container_name: abraka-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - abraka-network

  # Ollama - LLM service
  ollama:
    image: ollama/ollama:latest
    container_name: abraka-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - abraka-network

  # Zipkin - Distributed tracing (optional)
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: abraka-zipkin
    ports:
      - "9411:9411"
    networks:
      - abraka-network

  # Dapr placement service
  placement:
    image: daprio/dapr:1.14.4
    container_name: abraka-dapr-placement
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - abraka-network

  # Agent Shell - FastAPI service with Dapr sidecar
  agent-shell:
    build:
      context: .
      target: agent-shell
    container_name: abraka-agent-shell
    depends_on:
      redis:
        condition: service_healthy
      placement:
        condition: service_started
    environment:
      - SERVICE_NAME=agent-shell
      - AGENT_HTTP_PORT=8000
      - AGENT_SIDECAR_PORT=3500
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - abraka-network

  agent-shell-dapr:
    image: daprio/daprd:1.14.4
    container_name: abraka-agent-shell-dapr
    command: [
      "./daprd",
      "-app-id", "agent-shell",
      "-app-port", "8000",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "60000",
      "-placement-host-address", "placement:50006",
      "-components-path", "/components",
      "-config", "/config/config.yaml"
    ]
    volumes:
      - ./components/docker:/components
      - ./config:/config
    depends_on:
      - agent-shell
      - redis
      - placement
    network_mode: "service:agent-shell"

  # Workflow Host - Dapr Workflow service with Dapr sidecar
  workflow-host:
    build:
      context: .
      target: workflow-host
    container_name: abraka-workflow-host
    depends_on:
      redis:
        condition: service_healthy
      placement:
        condition: service_started
    environment:
      - SERVICE_NAME=workflow-host
      - WORKFLOW_SIDECAR_PORT=3601
      - PYTHONUNBUFFERED=1
    networks:
      - abraka-network

  workflow-host-dapr:
    image: daprio/daprd:1.14.4
    container_name: abraka-workflow-host-dapr
    command: [
      "./daprd",
      "-app-id", "workflow-host",
      "-dapr-http-port", "3601",
      "-dapr-grpc-port", "60001",
      "-placement-host-address", "placement:50006",
      "-components-path", "/components",
      "-config", "/config/config.yaml"
    ]
    volumes:
      - ./components/docker:/components
      - ./config:/config
    depends_on:
      - workflow-host
      - redis
      - placement
    network_mode: "service:workflow-host"

networks:
  abraka-network:
    driver: bridge

volumes:
  ollama-data:
