name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.8.19"
      - name: Sync dependencies
        run: uv sync --locked --all-extras
      - name: Lint
        run: uv run ruff check
      - name: Tests
        run: uv run pytest
